### ISSUE TITLE
does not match format '%Y-%m-%dT%H:%M:%S%z'

### ISSUE THREAD

**Issue by viasacra89** [rharkanson/pyriscope#23]
Traceback (most recent call last):
  File "/usr/local/bin/pyriscope", line 9, in <module>
    load_entry_point('pyriscope==1.2.10', 'console_scripts', 'pyriscope')()
  File "/usr/local/lib/python3.5/dist-packages/pyriscope/__main__.py", line 23, in main
    processor.process(args)
  File "/usr/local/lib/python3.5/dist-packages/pyriscope/processor.py", line 364, in process
    broadcast_start_time_dt = datetime.strptime(broadcast_start_time, '%Y-%m-%dT%H:%M:%S%z')
  File "/usr/lib/python3.5/_strptime.py", line 510, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.5/_strptime.py", line 343, in _strptime
    (data_string, format))
ValueError: time data '2017-01-10T06:23:15Z' does not match format '%Y-%m-%dT%H:%M:%S%z'

**Comment by RobRoy** [comment]
getting this aswell... on all URLs

**Comment by viasacra89** [comment]
Only workaround seems to be manually naming the files.

**Comment by sooqua** [comment]
I fixed it, however, I also added functionality to search for a non-existing file name by adding a number to it until one is found. If you don't want it just search and remove this `tempfilename = os.getcwd() + "\\" + name + ".ts"` + 7 lines below it.

**Comment by viasacra89** [comment]
Seem to be getting a new error with the fix.

Traceback (most recent call last):
  File "/usr/local/bin/pyriscope", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/pyriscope/__main__.py", line 23, in main
    processor.process(args)
  File "/usr/local/lib/python3.5/dist-packages/pyriscope/processor.py", line 364, in process
    broadcast_start_time_dt = datetime.strptime(broadcast_start_time, '%Y-%m-%dT%H:%M:%S%z')
  File "/usr/lib/python3.5/_strptime.py", line 510, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.5/_strptime.py", line 343, in _strptime
    (data_string, format))
ValueError: time data '2017-01-11T17:19:02Z' does not match format '%Y-%m-%dT%H:%M:%S%z'
