### ISSUE TITLE
Pyriscope does not stop recording after stream is done.

### ISSUE THREAD

**Issue by basil666** [rharkanson/pyriscope#26]
Sometimes, when a stream is concluded, recording will not stop even though it has already finished, and will not continue to the next step. (Which for me is usually conversion with the -C switch)

**Comment by francisuk1989** [comment]
I have the same issue but i can still play the TS format but dosnt seem to covert to MP4 with the -C command

When i know a broadcast is stopped, If i do "CTRL"and "C" I get this error (if any help)

sam@bigfootlap:/home/nce/ps# pyriscope http://periscope.tv/w/1SnAnLwwQzOxO -C
Recording stream to danny34youok (2017-04-17 21-29-15).live.ts                                                                                                 Traceback (most recent call last):
  File "/usr/local/bin/pyriscope", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/pyriscope/__main__.py", line 23, in main processor.process(args)
  File "/usr/local/lib/python3.5/dist-packages/pyriscope/processor.py", line 413, in process Popen(live_url, shell=True, stdout=PIPE).stdout.read() KeyboardInterrupt

again i can still play the TS video format in VLC but dosnt seem to covert to MP4 with the -C

Also using Ubuntu desktop 16.04.2 LTS x64
