### ISSUE TITLE
Unable to download past broadcasts

### ISSUE THREAD

**Issue by m4gnet98** [rharkanson/pyriscope#34]
It worked yesterday. Now it gives this error:
```
Downloading broadcast information.
Downloading replay information.
Traceback (most recent call last):
  File "c:\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python35\Scripts\pyriscope.exe\__main__.py", line 9, in <module>
  File "c:\python35\lib\site-packages\pyriscope\__main__.py", line 23, in main
    processor.process(args)
  File "c:\python35\lib\site-packages\pyriscope\processor.py", line 451, in process
    cookielist = access_public['cookies']
KeyError: 'cookies'
```

Example vod: https://www.pscp.tv/IVANJFOSTERs/1vAxRNZqgBvxl

**Comment by Vol-2016** [comment]
try "pscp." -> "periscope."

**Comment by m4gnet98** [comment]
Doesn't help. Is it working for you?

**Comment by acrocinus** [comment]
I have the same problem. Did you find any solutions?

**Comment by camconn** [comment]
I was able to bypass this issue by commenting out lines 455-461 in [processor.py](https://github.com/rharkanson/pyriscope/blob/4173366f5a89100ff1069f40b339824f5b80f18f/pyriscope/processor.py#L455). Just run `python3 -m pyriscope https://www.periscope.tv/w/myperiscopeurl`.

**Comment by mismail82** [comment]
Still doesn’t work.. any updates
