### ISSUE TITLE
Not works

### ISSUE THREAD

**Issue by ergoz** [rharkanson/pyriscope#4]
Command:
`pyriscope https://www.periscope.tv/w/1jhfgbkAfhYxL -C -r`

Answer:

```
Traceback (most recent call last):
  File "/usr/local/bin/pyriscope", line 7, in <module>
    from pyriscope.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/pyriscope/__main__.py", line 8, in <module>
    from pyriscope import processor
ImportError: cannot import name processor
```

and if i understand this script requires python 3+?

**Comment by tcplb** [comment]
on my pc requires python 3.5 only =/

**Comment by rharkanson** [comment]
It was written in/for Python 3.4.3. @ergoz seems to be trying to run the script with Python 2.7. If you have 3 installed, try installing it with your pip that manages your python 3 packages.

@tcplb Have you tried Python 3.4 at all? It shouldn't need 3.5.

**Comment by tcplb** [comment]
no no I tested just in 3.5

**Comment by rharkanson** [comment]
@tcplb Hmm, I'm not sure why that would be the case. I've tested it on multiple machines, all of which except one only have python 3.4 and I haven't experienced any issues with it. However, in @ergoz case, 2.7 will not run it.

**Comment by rharkanson** [comment]
I just tried setting up a quick virtual environment, using only 3.4.3, and it worked out fine.

```
$ /Library/Frameworks/Python.framework/Versions/3.4/bin/virtualenv env
Using base prefix '/Library/Frameworks/Python.framework/Versions/3.4'
New python executable in env/bin/python3.4
Also creating executable in env/bin/python
Installing setuptools, pip, wheel...done.

$ source env/bin/activate

(env)$ python -V
Python 3.4.3

(env)$ pip install pyriscope
Collecting pyriscope
  Using cached pyriscope-1.2.5-py2.py3-none-any.whl
Collecting six (from pyriscope)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting requests (from pyriscope)
  Using cached requests-2.8.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): wheel in ./env/lib/python3.4/site-packages (from pyriscope)
Collecting python-dateutil (from pyriscope)
  Using cached python_dateutil-2.4.2-py2.py3-none-any.whl
Installing collected packages: six, requests, python-dateutil, pyriscope
Successfully installed pyriscope-1.2.5 python-dateutil-2.4.2 requests-2.8.1 six-1.10.0

(env)$ pyriscope https://www.periscope.tv/w/1dRKZwjRWWQGB -C
Celest565 (2015-11-09 20-43-37).ts Downloaded!                                                                                                                  
Converted to Celest565 (2015-11-09 20-43-37).mp4!                                                                                                               
```
